// <auto-generated />
namespace HMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class identityframeworkrefernce : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(identityframeworkrefernce));
        
        string IMigrationMetadata.Id
        {
            get { return "202201180623176_identityframeworkrefernce"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
